name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup PEM File
        run: |
          echo "${{ secrets.EC2_PEM_KEY }}" > ec2-key.pem
          chmod 600 ec2-key.pem

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ec2-key.pem ec2-user@54.83.78.255 << 'EOF'

          # Kill any process running on port 4000
          sudo bash -c '
          PID=\$(lsof -t -i:4000 || true)
          if [ -n "\$PID" ]; then
            echo "Killing process on port 4000 (PID: \$PID)"
            kill -9 \$PID
          else
            echo "No process running on port 4000"
          fi
          '

          # Pull latest code
          sudo bash -c '
          cd /opt/houseoffitness/House-Of-Fitness-MERN-WebSite
          git config --global --add safe.directory /opt/houseoffitness/House-Of-Fitness-MERN-WebSite
          git pull origin main
          '

          # Install backend dependencies
          sudo bash -c '
          cd /opt/houseoffitness/House-Of-Fitness-MERN-WebSite/backend
          npm install
          '

          # Install frontend dependencies
          sudo bash -c '
          cd /opt/houseoffitness/House-Of-Fitness-MERN-WebSite/frontend
          npm install --legacy-peer-deps
          '

          # Start backend in detached mode
          sudo bash -c '
          cd /opt/houseoffitness/House-Of-Fitness-MERN-WebSite/backend
          nohup npm start -- --host 0.0.0.0 > backend.log 2>&1 < /dev/null &
          '

          EOF
