name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup PEM File
        run: |
          echo "${{ secrets.EC2_PEM_KEY }}" > ec2-key.pem
          chmod 600 ec2-key.pem

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ec2-key.pem ec2-user@54.83.78.255 << 'EOF'
          sudo -i

          # Kill process on port 4000 if running
          PID=\$(/usr/sbin/lsof -t -i:4000 || true)
          if [ -n "\$PID" ]; then
            echo "Killing process on port 4000 (PID: \$PID)"
            /bin/kill -9 \$PID
          else
            echo "No process running on port 4000"
          fi

          # Navigate to app directory
          cd /opt/houseoffitness/House-Of-Fitness-MERN-WebSite

          # Pull latest code
          git pull origin main

          # Backend setup
          cd /opt/houseoffitness/House-Of-Fitness-MERN-WebSite/backend
          npm install

          # Frontend setup
          cd /opt/houseoffitness/House-Of-Fitness-MERN-WebSite/frontend
          npm install --legacy-peer-deps

          # Start backend
          cd /opt/houseoffitness/House-Of-Fitness-MERN-WebSite/backend
          nohup npm start -- --host 0.0.0.0 &
          EOF
