name: Deploy to EC2
 
on:
  push:
    branches:
      - main
 
jobs:
  deploy:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
 
      - name: Setup PEM File
        run: |
          echo "${{ secrets.EC2_PEM_KEY }}" > ec2-key.pem
          chmod 600 ec2-key.pem

      - name: Kill process on port 4000
        run: |
          PID=$(lsof -t -i:4000)
          [ -n "$PID" ] && kill -9 $PID || echo "No process on port 4000"

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ec2-key.pem ec2-user@54.83.78.255 << 'EOF'
          sudo -i
          cd /opt/houseoffitness/House-Of-Fitness-MERN-WebSite
          git pull origin main
          cd /opt/houseoffitness/House-Of-Fitness-MERN-WebSite/backend
          npm install
          cd /opt/houseoffitness/House-Of-Fitness-MERN-WebSite/frontend
          npm install --legacy-peer-deps
          cd /opt/houseoffitness/House-Of-Fitness-MERN-WebSite/backend
          nohup npm start -- --host 0.0.0.0 & 
          EOF
